// <auto-generated />
using System;
using ChamadoX.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChamadoX.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250716013052_database2")]
    partial class database2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChamadoX.Models.CategoriaModel", b =>
                {
                    b.Property<string>("CategoriaId")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            CategoriaId = "suportetecnico",
                            Nome = "Suporte Técnico"
                        },
                        new
                        {
                            CategoriaId = "helpdesk",
                            Nome = "Helpdesk"
                        },
                        new
                        {
                            CategoriaId = "redes",
                            Nome = "Redes"
                        },
                        new
                        {
                            CategoriaId = "infraestrutura",
                            Nome = "Infraestrutura"
                        },
                        new
                        {
                            CategoriaId = "sistemas",
                            Nome = "Sistemas"
                        });
                });

            modelBuilder.Entity("ChamadoX.Models.StatusModel", b =>
                {
                    b.Property<string>("StatusId")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = "aberto",
                            Nome = "Aberto"
                        },
                        new
                        {
                            StatusId = "ematendimento",
                            Nome = "Em Atendimento"
                        },
                        new
                        {
                            StatusId = "finalizado",
                            Nome = "Finalizado"
                        });
                });

            modelBuilder.Entity("ChamadoX.Models.TiketModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoriaModelCategoriaId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataDeVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusModelStatusId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaModelCategoriaId");

                    b.HasIndex("StatusModelStatusId");

                    b.ToTable("Tiket");
                });

            modelBuilder.Entity("ChamadoX.Models.TiketModel", b =>
                {
                    b.HasOne("ChamadoX.Models.CategoriaModel", "CategoriaModel")
                        .WithMany()
                        .HasForeignKey("CategoriaModelCategoriaId");

                    b.HasOne("ChamadoX.Models.StatusModel", "StatusModel")
                        .WithMany()
                        .HasForeignKey("StatusModelStatusId");

                    b.Navigation("CategoriaModel");

                    b.Navigation("StatusModel");
                });
#pragma warning restore 612, 618
        }
    }
}
